export default {
	USER_ADMIN_CREATE,
	USER_ADMIN_UPDATE,
	USER_ADMIN_DELETE,

	USER_HOST_CREATE,
	USER_HOST_UPDATE,
	USER_HOST_DELETE,

    USER_HOST_ADDING_VACATIONS,
	USER_HOST_ADD_VACATIONS,

	USER_DRIVER_CREATE,
	USER_DRIVER_UPDATE,
	USER_DRIVER_DELETE,

    USER_PROCESSING,

	PLACE_CREATED,
	PLACE_UPDATED,
	PLACE_DELETED,

	PLACE_REQUEST_BOOKING,
	PLACE_CONFIRM_BOOKING,
	PLACE_REJECT_BOOKING,

	PLACE_CHANGE_STATUS,
	PLACE_PROCESSING,

	NOTIFICATIONS_CLEAR,
	NOTIFICATIONS_ACCEPTED,

	CONF_SET
}